[project]
name = "group-files-archiver"
version = "0.1.0"
description = "Tool to archive files of user group members"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.6",
    "pytest>=8.4.1",
]
